; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{51DDEB0E-DACD-4B4D-81B7-756AFF672F44}
AppName=MyCoinFlow
AppVersion=1.0.4
;AppVerName=MyCoinFlow 1.0.4
AppPublisher=brugilimSoft
AppPublisherURL=www.brugilim.ch
AppSupportURL=www.brugilim.ch
AppUpdatesURL=www.brugilim.ch
DefaultDirName={autopf}\MyCoinFlow
UninstallDisplayIcon={app}\MyCoinFlow.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\de\Lizenz.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\miche\OneDrive\Dokumente\MyCoinFlowUpdate
OutputBaseFilename=MyCoinFlow-Setup
SetupIconFile=C:\Dev\MyCoinFlow\MyCoinFlow\Assets\Icons\piggybank.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MyCoinFlow.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Azure.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Azure.Identity.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\ClosedXML.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\ClosedXML.Parser.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\CommunityToolkit.Mvvm.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\DocumentFormat.OpenXml.Framework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\ExcelDataReader.DataSet.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\ExcelDataReader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\ExcelNumberFormat.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\GLWpfControl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\HarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\LiveChartsCore.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\LiveChartsCore.SkiaSharpView.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\LiveChartsCore.SkiaSharpView.WPF.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MaterialDesignColors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MaterialDesignThemes.Wpf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Bcl.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Data.SqlClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Data.Tools.Sql.BatchParser.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.Caching.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.Caching.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Identity.Client.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Identity.Client.Extensions.Msal.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.JsonWebTokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.Protocols.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.IdentityModel.Tokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.ConnectionInfo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Dmf.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Dmf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.Collector.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.CollectorEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.HadrData.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.HadrModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.RegisteredServers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.Sdk.Sfc.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.SqlScriptPublish.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.XEvent.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.XEventDbScoped.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.XEventDbScopedEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Management.XEventEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.PolicyEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Server.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.ServiceBrokerEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Smo.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.Smo.Notebook.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.SmoExtended.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.SqlEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.SqlWmiManagement.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.SqlServer.WmiEnum.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Microsoft.Xaml.Behaviors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MyCoinFlow.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MyCoinFlow.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MyCoinFlow.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\MyCoinFlow.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\OpenTK.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\RBush.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\SixLabors.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\SkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\SkiaSharp.HarfBuzz.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\SkiaSharp.Views.Desktop.Common.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\SkiaSharp.Views.WPF.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\System.ClientModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\System.Data.OleDb.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\System.IdentityModel.Tokens.Jwt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Dev\MyCoinFlow\MyCoinFlow\bin\Debug\net9.0-windows\System.Management.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\.exe\OpenWithProgids"; ValueType: string; ValueName: "MyCoinFlow-Stup.exe"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\MyCoinFlow-Stup.exe"; ValueType: string; ValueName: ""; ValueData: "MyCoinFlow-Stup"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\MyCoinFlow-Stup.exe\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\MyCoinFlow.exe,0"
Root: HKA; Subkey: "Software\Classes\MyCoinFlow-Stup.exe\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\MyCoinFlow.exe"" ""%1"""

[Icons]
Name: "{autoprograms}\MyCoinFlow"; Filename: "{app}\MyCoinFlow.exe"
Name: "{autodesktop}\MyCoinFlow"; Filename: "{app}\MyCoinFlow.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\MyCoinFlow.exe"; Description: "{cm:LaunchProgram,MyCoinFlow}"; Flags: nowait postinstall skipifsilent

