using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using MyCoinFlow.Models;
using MyCoinFlow.Services;
using MyCoinFlow.WinUI.Models;

namespace MyCoinFlow.WinUI.Views;
public sealed partial class HouseholdPage : Page
{
    private readonly DatabaseService _database = new(); private bool _ready; private bool _loading;
    private string Section => (Sections.SelectedItem as TabViewItem)?.Tag as string ?? "Tasks";
    public HouseholdPage() { InitializeComponent(); Loaded += OnLoaded; }
    private async void OnLoaded(object sender, RoutedEventArgs e) { Sections.SelectedItem = TasksTab; NewButton.IsEnabled = false; UpdateActions(); if (_ready) return; _ready = true; try { await Task.Run(() => _database.EnsureHaushaltSchema()); await ReloadAsync(); } catch (Exception ex) { ShowStatus(ex.Message, InfoBarSeverity.Error); } }
    private async Task ReloadAsync(int? selectedId = null)
    {
        if (_loading) return;
        _loading = true;
        var selectedLocation = (LocationFilterBox.SelectedItem as HaushaltStandort)?.Id ?? 0; var selectedRoom = (RoomFilterBox.SelectedItem as HaushaltRaum)?.Id ?? 0;
        var locations = await Task.Run(() => _database.HaushaltStandorteGetAll()); LocationsList.ItemsSource = locations; LocationFilterBox.ItemsSource = new[] { new HaushaltStandort { Id = 0, Bezeichnung = "Alle Standorte" } }.Concat(locations).ToList(); LocationFilterBox.SelectedItem = ((IEnumerable<HaushaltStandort>)LocationFilterBox.ItemsSource).FirstOrDefault(value => value.Id == selectedLocation) ?? ((IEnumerable<HaushaltStandort>)LocationFilterBox.ItemsSource).First();
        var roomsAll = await Task.Run(() => _database.HaushaltRaeumeGetAll()); var rooms = selectedLocation > 0 ? roomsAll.Where(value => value.StandortId == selectedLocation).ToList() : roomsAll; RoomsList.ItemsSource = rooms; RoomFilterBox.ItemsSource = new[] { new HaushaltRaum { Id = 0, Bezeichnung = "Alle Räume" } }.Concat(rooms).ToList(); RoomFilterBox.SelectedItem = ((IEnumerable<HaushaltRaum>)RoomFilterBox.ItemsSource).FirstOrDefault(value => value.Id == selectedRoom) ?? ((IEnumerable<HaushaltRaum>)RoomFilterBox.ItemsSource).First();
        var objects = selectedRoom > 0 ? await Task.Run(() => _database.HaushaltObjekteGetByRaum(selectedRoom)) : await Task.Run(() => _database.HaushaltObjekteGetAll()); if (selectedLocation > 0 && selectedRoom == 0) { var ids = rooms.Select(value => value.Id).ToHashSet(); objects = objects.Where(value => ids.Contains(value.RaumId)).ToList(); } ObjectsList.ItemsSource = objects;
        var tasks = await Task.Run(() => _database.HaushaltOffeneAufgabenGetAll()); TasksList.ItemsSource = tasks.Select(value => new HouseholdTaskTile(value)).ToList(); CategoriesList.ItemsSource = await Task.Run(() => _database.HaushaltObjektKategorienGetAll()); InstructionsList.ItemsSource = await Task.Run(() => _database.HaushaltArbeitsanweisungenGetAll()); IntervalsList.ItemsSource = await Task.Run(() => _database.HaushaltZeitintervalleGetAll());
        SelectById(selectedId); ResultText.Text = $"{objects.Count} Objekte · {tasks.Count} offene Aufgaben"; UpdateActions(); _loading = false;
    }
    private void SelectById(int? id) { if (!id.HasValue) return; switch (Section) { case "Tasks": TasksList.SelectedItem = ((IEnumerable<HouseholdTaskTile>)TasksList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Locations": LocationsList.SelectedItem = ((IEnumerable<HaushaltStandort>)LocationsList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Rooms": RoomsList.SelectedItem = ((IEnumerable<HaushaltRaum>)RoomsList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Objects": ObjectsList.SelectedItem = ((IEnumerable<HaushaltObjekt>)ObjectsList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Categories": CategoriesList.SelectedItem = ((IEnumerable<HaushaltObjektKategorie>)CategoriesList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Instructions": InstructionsList.SelectedItem = ((IEnumerable<HaushaltArbeitsanweisung>)InstructionsList.ItemsSource).FirstOrDefault(value => value.Id == id); break; case "Intervals": IntervalsList.SelectedItem = ((IEnumerable<HaushaltZeitintervall>)IntervalsList.ItemsSource).FirstOrDefault(value => value.Id == id); break; } }
    private async void OnRefreshClick(object sender, RoutedEventArgs e) => await ReloadAsync(); private async void OnLocationFilterChanged(object sender, SelectionChangedEventArgs e) { if (_ready && !_loading) await ReloadAsync(); } private async void OnRoomFilterChanged(object sender, SelectionChangedEventArgs e) { if (_ready && !_loading) await ReloadAsync(); }
    private void OnSectionChanged(object sender, SelectionChangedEventArgs e) { if (!ReferenceEquals(e.OriginalSource, Sections)) return; NewButton.IsEnabled = Section != "Tasks"; NewButton.Label = Section == "Objects" ? "Objekt neu" : "Neu"; UpdateActions(); }
    private void OnListSelectionChanged(object sender, SelectionChangedEventArgs e) => UpdateActions();
    private object? Selected => Section switch { "Locations" => LocationsList.SelectedItem, "Rooms" => RoomsList.SelectedItem, "Objects" => ObjectsList.SelectedItem, "Tasks" => TasksList.SelectedItem, "Categories" => CategoriesList.SelectedItem, "Instructions" => InstructionsList.SelectedItem, "Intervals" => IntervalsList.SelectedItem, _ => null };
    private void UpdateActions() { EditButton.IsEnabled = DeleteButton.IsEnabled = Selected is not null && Section != "Tasks"; }
    private async void OnNewClick(object sender, RoutedEventArgs e) => await EditAsync(null);
    private async void OnEditClick(object sender, RoutedEventArgs e) => await EditAsync(Selected);
    private async Task EditAsync(object? source)
    {
        switch (Section)
        {
            case "Locations": { var value = source as HaushaltStandort; var d = new HouseholdMasterEditorDialog(HouseholdMasterKind.Location, value?.Bezeichnung ?? "", value?.IconKey ?? "", value?.FarbeKey ?? "", description: value?.Bemerkung ?? "") { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary) return; var model = new HaushaltStandort { Id = value?.Id ?? 0, Bezeichnung = d.ValueName, IconKey = d.Icon, FarbeKey = d.Color, Bemerkung = d.Description, IstAktiv = true }; var id = value is null ? _database.HaushaltStandortInsert(model) : value.Id; if (value is not null) _database.HaushaltStandortUpdate(model); await ReloadAsync(id); break; }
            case "Rooms": { var value = source as HaushaltRaum; var location = LocationFilterBox.SelectedItem as HaushaltStandort; if (value is null && location is not { Id: > 0 }) { await MessageAsync("Raum", "Bitte zuerst einen Standort auswählen."); return; } var d = new HouseholdMasterEditorDialog(HouseholdMasterKind.Room, value?.Bezeichnung ?? "", value?.IconKey ?? "", description: value?.Bemerkung ?? "") { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary) return; var model = new HaushaltRaum { Id = value?.Id ?? 0, StandortId = value?.StandortId ?? location?.Id, Bezeichnung = d.ValueName, IconKey = d.Icon, Bemerkung = d.Description, IstAktiv = true }; var id = value is null ? _database.HaushaltRaumInsert(model) : value.Id; if (value is not null) _database.HaushaltRaumUpdate(model); await ReloadAsync(id); break; }
            case "Objects": { var value = source as HaushaltObjekt; var roomId = (RoomFilterBox.SelectedItem as HaushaltRaum)?.Id; var d = new HouseholdObjectEditorDialog(roomId > 0 ? roomId : null, value) { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary || d.Result is null) return; var id = value is null ? _database.HaushaltObjektInsert(d.Result) : value.Id; if (value is not null) _database.HaushaltObjektUpdate(d.Result); d.Result.Id = id; new HaushaltAufgabenService(_database).AufgabeFuerObjektErzeugenWennNoetig(d.Result); await ReloadAsync(id); break; }
            case "Categories": { var value = source as HaushaltObjektKategorie; var d = new HouseholdMasterEditorDialog(HouseholdMasterKind.Category, value?.Bezeichnung ?? "", value?.IconKey ?? "", description: value?.Bemerkung ?? "") { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary) return; var model = new HaushaltObjektKategorie { Id = value?.Id ?? 0, Bezeichnung = d.ValueName, IconKey = d.Icon, Bemerkung = d.Description, IstAktiv = true }; var id = value is null ? _database.HaushaltObjektKategorieInsert(model) : value.Id; if (value is not null) _database.HaushaltObjektKategorieUpdate(model); await ReloadAsync(id); break; }
            case "Instructions": { var value = source as HaushaltArbeitsanweisung; var d = new HouseholdMasterEditorDialog(HouseholdMasterKind.Instruction, value?.Bezeichnung ?? "", value?.IconKey ?? "", description: value?.Beschreibung ?? "") { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary) return; var model = new HaushaltArbeitsanweisung { Id = value?.Id ?? 0, Bezeichnung = d.ValueName, IconKey = d.Icon, Beschreibung = d.Description, IstAktiv = true }; var id = value is null ? _database.HaushaltArbeitsanweisungInsert(model) : value.Id; if (value is not null) _database.HaushaltArbeitsanweisungUpdate(model); await ReloadAsync(id); break; }
            case "Intervals": { var value = source as HaushaltZeitintervall; var d = new HouseholdMasterEditorDialog(HouseholdMasterKind.Interval, value?.Bezeichnung ?? "", days: value?.Tage ?? 1, description: value?.Bemerkung ?? "") { XamlRoot = XamlRoot }; if (await d.ShowAsync() != ContentDialogResult.Primary) return; var model = new HaushaltZeitintervall { Id = value?.Id ?? 0, Bezeichnung = d.ValueName, Tage = d.Days, Bemerkung = d.Description, IstAktiv = true }; var id = value is null ? _database.HaushaltZeitintervallInsert(model) : value.Id; if (value is not null) _database.HaushaltZeitintervallUpdate(model); await ReloadAsync(id); break; }
        }
    }
    private async void OnDeleteClick(object sender, RoutedEventArgs e) { if (Selected is null || !await ConfirmAsync("Löschen bestätigen", "Der ausgewählte Eintrag wird gelöscht.")) return; try { switch (Selected) { case HaushaltStandort x: _database.HaushaltStandortDelete(x.Id); break; case HaushaltRaum x: _database.HaushaltRaumDelete(x.Id); break; case HaushaltObjekt x: _database.HaushaltObjektDelete(x.Id); break; case HaushaltObjektKategorie x: _database.HaushaltObjektKategorieDelete(x.Id); break; case HaushaltArbeitsanweisung x: _database.HaushaltArbeitsanweisungDelete(x.Id); break; case HaushaltZeitintervall x: _database.HaushaltZeitintervallDelete(x.Id); break; } await ReloadAsync(); } catch (Exception ex) { ShowStatus(ex.Message, InfoBarSeverity.Error); } }
    private async void OnUpdateTasksClick(object sender, RoutedEventArgs e) { var count = await Task.Run(() => new HaushaltAufgabenService(_database).AufgabenFuerAlleObjekteAktualisieren(_database.HaushaltObjekteGetAll())); await ReloadAsync(); await MessageAsync("Haushalt Aufgaben", $"Aufgaben aktualisiert.\n\nNeu erstellt: {count}"); }
    private async void OnCompleteTaskClick(object sender, RoutedEventArgs e) { if (TasksList.SelectedItem is not HouseholdTaskTile tile) { await MessageAsync("Aufgabe erledigen", "Bitte zuerst eine Aufgabe auswählen."); return; } await CompleteTaskAsync(tile.Value); }
    private async void OnCompleteTaskTileClick(object sender, RoutedEventArgs e) { if (sender is Button { Tag: HaushaltAufgabe task }) await CompleteTaskAsync(task); }
    private async Task CompleteTaskAsync(HaushaltAufgabe task) { if (!await ConfirmAsync("Aufgabe erledigen", $"Soll die Aufgabe „{task.Titel}“ als heute erledigt markiert werden?")) return; var today = DateTime.Today; _database.HaushaltAufgabeErledigen(task.Id, today); _database.HaushaltObjektLetzteAusfuehrungSetzen(task.ObjektId, today); new HaushaltAufgabenService(_database).AufgabenFuerAlleObjekteAktualisieren(_database.HaushaltObjekteGetAll()); await ReloadAsync(); }
    private async Task<bool> ConfirmAsync(string title, string text) => await new ContentDialog { XamlRoot = XamlRoot, Title = title, Content = text, PrimaryButtonText = "Ja", CloseButtonText = "Nein", DefaultButton = ContentDialogButton.Close }.ShowAsync() == ContentDialogResult.Primary; private async Task MessageAsync(string title, string text) => await new ContentDialog { XamlRoot = XamlRoot, Title = title, Content = text, CloseButtonText = "Schließen" }.ShowAsync(); private void ShowStatus(string message, InfoBarSeverity severity) { StatusBar.Message = message; StatusBar.Severity = severity; StatusBar.IsOpen = true; }
}
