using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using MyCoinFlow.Services;
using MyCoinFlow.Services.Update;
using MyCoinFlow.WinUI.Services;
using System.Diagnostics;
using System.Globalization;

namespace MyCoinFlow.WinUI.Views;

public sealed partial class PathsSettingsControl : UserControl
{
    private const string KeyRoot = "AttachmentRoot", KeyMax = "AttachmentMaxMB", KeyTessExe = "TesseractExePath", KeyTessLang = "TesseractLanguages", KeyWorkFolder = "DmsWorkingFolder", KeyWatcherEnabled = "DmsWatcherEnabled";
    private readonly DatabaseService _database = new(); private readonly AttachmentService _attachments = new();
    public PathsSettingsControl() { InitializeComponent(); try { _database.EnsureAttachmentsSchema(); } catch { } LoadSettings(); LoadStats(); }
    private void LoadSettings() { var root = _database.GetAppSetting(KeyRoot); if (string.IsNullOrWhiteSpace(root)) root = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "MyCoinFlow", "Attachments"); AttachmentRootBox.Text = root; MaxMbBox.Text = _database.GetAppSetting(KeyMax) ?? "20"; var defaultTesseract = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "OCR", "tesseract.exe"); TesseractPathBox.Text = _database.GetAppSetting(KeyTessExe) ?? defaultTesseract; LanguagesBox.Text = _database.GetAppSetting(KeyTessLang) ?? "deu+eng"; WorkFolderBox.Text = _database.GetAppSetting(KeyWorkFolder) ?? string.Empty; var enabled = _database.GetAppSetting(KeyWatcherEnabled); WatcherEnabledBox.IsChecked = string.IsNullOrWhiteSpace(enabled) || enabled == "1"; }
    private void OnSavePathsClick(object sender, RoutedEventArgs e) { try { var root = AttachmentRootBox.Text.Trim(); if (string.IsNullOrWhiteSpace(root) || !int.TryParse(MaxMbBox.Text.Trim(), out var mb) || mb < 1 || mb > 1024) { Show("Bitte einen Zielordner und eine Maximalgröße von 1–1024 MB erfassen.", InfoBarSeverity.Warning); return; } Directory.CreateDirectory(root); var work = WorkFolderBox.Text.Trim(); if (!string.IsNullOrWhiteSpace(work)) Directory.CreateDirectory(work); _database.SetAppSetting(KeyRoot, root); _database.SetAppSetting(KeyMax, mb.ToString(CultureInfo.InvariantCulture)); _database.SetAppSetting(KeyWorkFolder, string.IsNullOrWhiteSpace(work) ? null : work); _database.SetAppSetting(KeyWatcherEnabled, WatcherEnabledBox.IsChecked == true ? "1" : "0"); DmsWatcherService.Instance.Restart(); Show("Verzeichnis-Einstellungen gespeichert.", InfoBarSeverity.Success); } catch (Exception ex) { Show(ex.Message, InfoBarSeverity.Error); } }
    private void OnCreateAttachmentFolderClick(object sender, RoutedEventArgs e) => CreateFolder(AttachmentRootBox.Text, "Ordner"); private void OnCreateWorkFolderClick(object sender, RoutedEventArgs e) => CreateFolder(WorkFolderBox.Text, "Arbeitsordner");
    private void CreateFolder(string path, string name) { try { if (string.IsNullOrWhiteSpace(path)) { Show($"Bitte zuerst einen {name}-Pfad eingeben.", InfoBarSeverity.Warning); return; } Directory.CreateDirectory(path.Trim()); Show($"{name} ist vorhanden.", InfoBarSeverity.Success); } catch (Exception ex) { Show(ex.Message, InfoBarSeverity.Error); } }
    private void OnOpenAttachmentFolderClick(object sender, RoutedEventArgs e) => OpenFolder(AttachmentRootBox.Text); private void OnOpenWorkFolderClick(object sender, RoutedEventArgs e) => OpenFolder(WorkFolderBox.Text);
    private void OpenFolder(string path) { try { if (!Directory.Exists(path.Trim())) { Show("Ordner nicht gefunden.", InfoBarSeverity.Warning); return; } Process.Start(new ProcessStartInfo("explorer.exe", $"\"{path.Trim()}\"") { UseShellExecute = true }); } catch (Exception ex) { Show(ex.Message, InfoBarSeverity.Error); } }
    private void OnSuggestOneDriveClick(object sender, RoutedEventArgs e) { var root = UpdatePathResolver.GetOneDriveRoot(); if (string.IsNullOrWhiteSpace(root)) { Show("Kein OneDrive-Ordner auf diesem PC gefunden.", InfoBarSeverity.Warning); return; } AttachmentRootBox.Text = Path.Combine(root, "MyCoinFlow", "Dokumente"); Show("OneDrive-Ordner eingetragen. Bitte Ordner erstellen und danach speichern.", InfoBarSeverity.Informational); }
    private async void OnMigrateNamesClick(object sender, RoutedEventArgs e) { var dialog = new ContentDialog { XamlRoot = XamlRoot, Title = "Dateinamen vereinheitlichen", Content = "Alle bestehenden Dokumente werden auf das Namensschema DOK-{Id} umgestellt. Bereits korrekt benannte Dokumente werden übersprungen.", PrimaryButtonText = "Fortfahren", CloseButtonText = "Abbrechen" }; if (await dialog.ShowAsync() != ContentDialogResult.Primary) return; try { var result = _attachments.MigrateAllToUniformNaming(); Show($"{result.Renamed} umbenannt, {result.AlreadyOk} bereits korrekt, {result.Missing} übersprungen.", result.Missing > 0 ? InfoBarSeverity.Warning : InfoBarSeverity.Success); } catch (Exception ex) { Show(ex.Message, InfoBarSeverity.Error); } }
    private async void OnBrowseTesseractClick(object sender, RoutedEventArgs e) { TesseractPathBox.Text = await FilePickerService.PickOpenAsync(".exe") ?? TesseractPathBox.Text; }
    private void OnSaveOcrClick(object sender, RoutedEventArgs e) { var path = TesseractPathBox.Text.Trim(); var languages = LanguagesBox.Text.Trim(); if (!path.EndsWith("tesseract.exe", StringComparison.OrdinalIgnoreCase) || !File.Exists(path)) { Show("tesseract.exe wurde am angegebenen Pfad nicht gefunden.", InfoBarSeverity.Warning); return; } _database.SetAppSetting(KeyTessExe, path); _database.SetAppSetting(KeyTessLang, string.IsNullOrWhiteSpace(languages) ? "deu+eng" : languages); Show("OCR-Einstellungen gespeichert.", InfoBarSeverity.Success); }
    private async void OnReindexClick(object sender, RoutedEventArgs e) { try { var progress = new Progress<(int done, int total, int withText, int images, int errors, int skipped)>(value => Show($"Index: {value.done}/{value.total} – Text:{value.withText}, Bild-OCR:{value.images}, Fehler:{value.errors}, übersprungen:{value.skipped}", InfoBarSeverity.Informational)); var result = await new OcrService().IndexMissingAsync(progress); Show($"Index fertig: {result.done}/{result.total} – Text:{result.withText}, Bild-OCR:{result.images}, Fehler:{result.errors}, übersprungen:{result.skipped}", result.errors > 0 ? InfoBarSeverity.Warning : InfoBarSeverity.Success); LoadStats(); } catch (Exception ex) { Show("Index fehlgeschlagen: " + ex.Message, InfoBarSeverity.Error); } }
    private void OnRefreshStatsClick(object sender, RoutedEventArgs e) => LoadStats();
    private void LoadStats() { try { var value = _database.GetDatabaseStats(); DatabaseNameText.Text = value.DatabaseName; DatabaseSizeText.Text = $"{value.DataSizeMB:N2} MB"; DatabaseLimitText.Text = $"{value.DataMaxMB:N0} MB"; var percent = value.DataMaxMB > 0 ? Math.Clamp(value.DataSizeMB / value.DataMaxMB * 100d, 0d, 100d) : 0d; DatabaseUsageBar.Value = percent; DatabaseUsageText.Text = $"{percent:N1}% genutzt"; AttachmentCountText.Text = value.AttachmentCount.ToString("N0"); AttachmentTextCountText.Text = value.AttachmentTextCount.ToString("N0"); TextSizeText.Text = $"{value.AttachmentTextBytes / (1024d * 1024d):N2} MB"; } catch (Exception ex) { Show("DB-Status konnte nicht geladen werden: " + ex.Message, InfoBarSeverity.Error); } }
    private void Show(string message, InfoBarSeverity severity) { StatusBar.Message = message; StatusBar.Severity = severity; StatusBar.IsOpen = true; }
}
